<a href="https://colab.research.google.com/github/yprogbest/udemy_pandas/blob/main/pandasNote01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#メモ
#Series(1次元)とDataFrame(2次元)が重要！
import pandas as pd

# Seriesの作成

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


## リストからSeriesを作成する

In [ ]:
lst1 = [1,2,3,4,5]

In [ ]:
lst1

[1, 2, 3, 4, 5]

In [ ]:
lst2 = [x**2 for x in lst1]
print(lst2)

[1, 4, 9, 16, 25]


In [ ]:
sr = pd.Series(lst2, index=lst1)

In [ ]:
sr

1     1
2     4
3     9
4    16
5    25
dtype: int64

In [ ]:
sr0 = pd.Series(lst2)
sr0

0     1
1     4
2     9
3    16
4    25
dtype: int64

## インデックスを指定して、要素にアクセスする

In [ ]:
sr

1     1
2     4
3     9
4    16
5    25
dtype: int64

In [ ]:
sr.at[5]

25

In [ ]:
sr.loc[2:4]

2     4
3     9
4    16
dtype: int64

In [ ]:
sr.at[2] = 999
sr

1      1
2    999
3      9
4     16
5     25
dtype: int64

In [ ]:
sr.loc[2:4] = [555, 666, 777]
sr

1      1
2    555
3    666
4    777
5     25
dtype: int64

## 数値以外の値をインデックスにする

In [ ]:
words = pd.Series(['りんご', 'みかん', 'ぶどう'], index=['apple', 'orange', 'grape'])
words

apple     りんご
orange    みかん
grape     ぶどう
dtype: object

In [ ]:
words.at['apple']

'りんご'

### ドットによるインデックスの指定（非数値のインデックス）

In [ ]:
words.apple

'りんご'

In [ ]:
# ドットによるアクセスでは新規要素の追加は出来ない
words.watermelon = 'すいか'
words

apple     りんご
orange    みかん
grape     ぶどう
dtype: object

In [ ]:
words.at['watermelon'] = 'すいか'
words

apple         りんご
orange        みかん
grape         ぶどう
watermelon    すいか
dtype: object

In [ ]:
words.grape = '葡萄'
words

apple         りんご
orange        みかん
grape          葡萄
watermelon    すいか
dtype: object

## 格納順位を指定して要素にアクセスする

In [ ]:
sr

1      1
2    555
3    666
4    777
5     25
dtype: int64

In [ ]:
sr.iat[0]

1

In [ ]:
sr.iloc[1:4]

2    555
3    666
4    777
dtype: int64

# 演習1

## ステップ1

In [ ]:
import sympy
p = list(sympy.primerange(1,100))
print(p)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


## ステップ2

In [ ]:
idx = list(range(1,len(p)+1))

print(idx)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]


## ステップ3

In [ ]:
sp = pd.Series(p, index=idx)
print(sp)

1      2
2      3
3      5
4      7
5     11
6     13
7     17
8     19
9     23
10    29
11    31
12    37
13    41
14    43
15    47
16    53
17    59
18    61
19    67
20    71
21    73
22    79
23    83
24    89
25    97
dtype: int64


## ステップ4

In [ ]:
sp.at[20]

71

In [ ]:
sp.iloc[15:20]

16    53
17    59
18    61
19    67
20    71
dtype: int64

# スライスの記述によるSeriesオブジェクトの要素へのアクセス

## リストの場合

In [ ]:
lst = ['a', 'b', 'c', 'd', 'e']

In [ ]:
lst[0]

'a'

In [ ]:
# リストの使い方と同様に扱うことができる
sr01 = pd.Series([2,4,6,8,10], index=[0,1,2,3,4])
sr02 = pd.Series([2,4,6,8,10], index=[1,2,3,4,5])

In [ ]:
sr01[0:3]

0    2
1    4
2    6
dtype: int64

In [ ]:
sr02[0:3]

1    2
2    4
3    6
dtype: int64

In [ ]:
sr01.iloc[0:3]

0    2
1    4
2    6
dtype: int64

In [ ]:
sr02.iloc[0:3]

1    2
2    4
3    6
dtype: int64

# 条件指定による要素の抽出

In [ ]:
sr

1      1
2    555
3    666
4    777
5     25
dtype: int64

## 真理値のよるマスキング

In [ ]:
msk = [True, True, False, False, True] #抽出対象の要素を真理値で指定

In [ ]:
sr.iloc[msk]

1      1
2    555
5     25
dtype: int64

### Seriesに対する条件判定

In [ ]:
sr < 100

1     True
2    False
3    False
4    False
5     True
dtype: bool

### スライスの中に条件式を記述する

In [ ]:
sr[sr<100]

1     1
5    25
dtype: int64

In [ ]:
# sr.iloc[sr<100] #ilocには条件式を指定できない
# sr.iat[sr<100] #iatにも条件式を指定できない
sr.loc[sr<100]

1     1
5    25
dtype: int64

# 重複するインデックスを持つSeriesの扱い

In [ ]:
lst2

[1, 4, 9, 16, 25]

In [ ]:
#重複する要素を持つリスト
ix2 = ['x', 'y', 'y', 'y', 'z']

In [ ]:
sr2 = pd.Series(lst2, index=ix2)
sr2

x     1
y     4
y     9
y    16
z    25
dtype: int64

In [ ]:
sr2.at['y']

y     4
y     9
y    16
dtype: int64

In [ ]:
sr2.loc['y']

y     4
y     9
y    16
dtype: int64

# Seriesの内部構造

In [ ]:
sr2

x     1
y     4
y     9
y    16
z    25
dtype: int64

## 値の並びをNumpyの配列として取り出す

In [ ]:
sr2.values

array([ 1,  4,  9, 16, 25])

In [ ]:
type(sr2.values)

numpy.ndarray

## インデックスを明に取り出す

In [ ]:
ix = sr2.index
ix

Index(['x', 'y', 'y', 'y', 'z'], dtype='object')

In [ ]:
type(ix)

pandas.core.indexes.base.Index

### インデックスオブジェクトにはスライスが使える

In [ ]:
ix[4]

'z'

In [ ]:
ix[1:]

Index(['y', 'y', 'y', 'z'], dtype='object')

### インデックスの内容をNumpyの配列のとして取り出す

In [ ]:
ix.values

array(['x', 'y', 'y', 'y', 'z'], dtype=object)

## インデックスの検索

In [ ]:
sr2

x     1
y     4
y     9
y    16
z    25
dtype: int64

In [ ]:
sr2.index.get_loc('x')

0

### 重複するインデックス項目がある場合（1）

In [ ]:
sr2.index.get_loc('y')

slice(1, 4, None)

### 参考）スライスオブジェクト

In [ ]:
a = [1,2,3,4,5,6,7]
a[1:7:2]

[2, 4, 6]

In [ ]:
s = slice(1,7,2)
a[s]

[2, 4, 6]

### 重複するインデックスがある場合（2）

In [ ]:
sr22 = pd.Series(range(9), index = ['x', 'y', 'x', 'x', 'y', 'y', 'z', 'y', 'z'])
sr22

x    0
y    1
x    2
x    3
y    4
y    5
z    6
y    7
z    8
dtype: int64

In [ ]:
sr22.index.get_loc('y')

array([False,  True, False, False,  True,  True, False,  True, False])

# Numpyの一次元配列をSeriesに変換する

In [ ]:
import numpy as np
ar = np.array([2,4,6,8,10], dtype='float64')
ar

array([ 2.,  4.,  6.,  8., 10.])

In [ ]:
sr3 = pd.Series(ar)
sr3

0     2.0
1     4.0
2     6.0
3     8.0
4    10.0
dtype: float64

# 整列処理（ソート）

In [ ]:
sr4 = pd.Series([25, 1, 16, 4, 9])
sr4

0    25
1     1
2    16
3     4
4     9
dtype: int64

In [ ]:
sr41 = sr4.sort_values()
sr41

1     1
3     4
4     9
2    16
0    25
dtype: int64

In [ ]:
sr4

0    25
1     1
2    16
3     4
4     9
dtype: int64

In [ ]:
sr42 = sr4.sort_values(ascending=False)
sr42

0    25
2    16
4     9
3     4
1     1
dtype: int64

## インデックスの順に整列

In [ ]:
sr42.sort_index()

0    25
1     1
2    16
3     4
4     9
dtype: int64

In [ ]:
sr42.sort_index(ascending=False)

4     9
3     4
2    16
1     1
0    25
dtype: int64

In [ ]:
sr2

x     1
y     4
y     9
y    16
z    25
dtype: int64

In [ ]:
sr2.index

Index(['x', 'y', 'y', 'y', 'z'], dtype='object')

In [ ]:
sr2.index.to_numpy()

array(['x', 'y', 'y', 'y', 'z'], dtype=object)

# Seriesの要素の削除

In [ ]:
sr5 = pd.Series([111,222,333], index=['d1', 'd2', 'd3'])
sr5

d1    111
d2    222
d3    333
dtype: int64

In [ ]:
sr51 = sr5.drop('d2')
sr51

d1    111
d3    333
dtype: int64

In [ ]:
sr52 = sr5.drop(['d1', 'd3'])
sr52

d2    222
dtype: int64

## 対象のSeriesの要素を直接的に削除する

In [ ]:
del sr5['d2']
sr5

d1    111
d3    333
dtype: int64

# Seriesオブジェクトの連結

In [ ]:
srA = pd.Series([11,12,13])
srB = pd.Series([21,22,33])

In [ ]:
srA

0    11
1    12
2    13
dtype: int64

In [ ]:
srB

0    21
1    22
2    33
dtype: int64

In [ ]:
srAB = pd.concat([srA,srB])
srAB

0    11
1    12
2    13
0    21
1    22
2    33
dtype: int64

# インデックスの再設定

## 最も単純な方法（整数インデックス）

In [ ]:
srAB2 = srAB.reset_index(drop=True)
srAB2

0    11
1    12
2    13
3    21
4    22
5    33
dtype: int64

## drop=を省略した場合

In [ ]:
df1 = srAB.reset_index()
df1

index   0
0      0  11
1      1  12
2      2  13
3      0  21
4      1  22
5      2  33

In [ ]:
type(df1)

pandas.core.frame.DataFrame

## 与えた項目列でインデックスを置き換える方法

In [ ]:
srAB

0    11
1    12
2    13
0    21
1    22
2    33
dtype: int64

In [ ]:
srAB.index = ['a', 'b', 'c', 'd', 'e', 'f']
srAB

a    11
b    12
c    13
d    21
e    22
f    33
dtype: int64

# 開始部分/終了部分の取り出し

In [ ]:
sr6 = pd.Series([x**2 for x in range(100)])
sr6

0        0
1        1
2        4
3        9
4       16
      ... 
95    9025
96    9216
97    9409
98    9604
99    9801
Length: 100, dtype: int64

In [ ]:
sr6.head(10)

0     0
1     1
2     4
3     9
4    16
5    25
6    36
7    49
8    64
9    81
dtype: int64

In [ ]:
sr6.tail(10)

90    8100
91    8281
92    8464
93    8649
94    8836
95    9025
96    9216
97    9409
98    9604
99    9801
dtype: int64

# マルチインデックス

## MultiIndexオブジェクトの作成

In [ ]:
midx = pd.MultiIndex.from_tuples([
    ('A', 'a', 1),
    ('A', 'a', 2),
    ('A', 'b', 1),
    ('A', 'b', 2),
    ('B', 'a', 1),
    ('B', 'a', 2),
    ('B', 'b', 1),
    ('B', 'b', 2)
])

In [ ]:
midx

MultiIndex([('A', 'a', 1),
            ('A', 'a', 2),
            ('A', 'b', 1),
            ('A', 'b', 2),
            ('B', 'a', 1),
            ('B', 'a', 2),
            ('B', 'b', 1),
            ('B', 'b', 2)],
           )

## マルチインデックスを持つSeriesを作成する

In [ ]:
sr = pd.Series(range(8), index=midx)
sr

A  a  1    0
      2    1
   b  1    2
      2    3
B  a  1    4
      2    5
   b  1    6
      2    7
dtype: int64

## カテゴリー（インデックスレベル）毎にデータを取り出す

In [ ]:
sr.at[('A')]

a  1    0
   2    1
b  1    2
   2    3
dtype: int64

In [ ]:
sr.at[('A','b')]

1    2
2    3
dtype: int64

In [ ]:
sr.at[('A','b', 2)]

3

## インデックスレベルを指定した整列

In [ ]:
sr

A  a  1    0
      2    1
   b  1    2
      2    3
B  a  1    4
      2    5
   b  1    6
      2    7
dtype: int64

In [ ]:
sr.sort_index(level=1)

A  a  1    0
      2    1
B  a  1    4
      2    5
A  b  1    2
      2    3
B  b  1    6
      2    7
dtype: int64

In [ ]:
sr.sort_index(level=2)

A  a  1    0
   b  1    2
B  a  1    4
   b  1    6
A  a  2    1
   b  2    3
B  a  2    5
   b  2    7
dtype: int64

## 各インデックスレベルに名前を与える

In [ ]:
midx = pd.MultiIndex.from_tuples([
    ('A', 'a', 1),
    ('A', 'a', 2),
    ('A', 'b', 1),
    ('A', 'b', 2),
    ('B', 'a', 1),
    ('B', 'a', 2),
    ('B', 'b', 1),
    ('B', 'b', 2)
],names=['1st', '2nd', '3rd'])

In [ ]:
midx

MultiIndex([('A', 'a', 1),
            ('A', 'a', 2),
            ('A', 'b', 1),
            ('A', 'b', 2),
            ('B', 'a', 1),
            ('B', 'a', 2),
            ('B', 'b', 1),
            ('B', 'b', 2)],
           names=['1st', '2nd', '3rd'])

In [ ]:
sr = pd.Series(range(8), index=midx)
sr

1st  2nd  3rd
A    a    1      0
          2      1
     b    1      2
          2      3
B    a    1      4
          2      5
     b    1      6
          2      7
dtype: int64

In [ ]:
sr.sort_index(level='3rd')

1st  2nd  3rd
A    a    1      0
     b    1      2
B    a    1      4
     b    1      6
A    a    2      1
     b    2      3
B    a    2      5
     b    2      7
dtype: int64